<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit214f688fac3c2e7a9e19d853b1b64e57
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit214f688fac3c2e7a9e19d853b1b64e57::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit214f688fac3c2e7a9e19d853b1b64e57::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit214f688fac3c2e7a9e19d853b1b64e57::$classMap;

        }, null, ClassLoader::class);
    }
}
